# Blog info
blog_name: Yanda's Lab
slogan: The existence of this blog fills you with determination
url: http://yodahuang.github.io
language: en

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /favicon.ico

# For seo
#I don't know what I should advertise
keywords:

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #Don't open in a new page
  - name: Project
    url: /project/
    target_blank: true #Open in a new page
  - name: About me
    url: /about/
    target_blank: false
  - name: My Aria2
    url: http://45.79.103.183/aria2/
    target_blank: true

# config page nav
page_nav:
  - name: Blog
    url: /archives/
    target_blank: false
  - name: Project
    url: /project/
    target_blank: true #Open in a new page
  - name: Category
    url: /category/
    target_blank: false
  - name: Tag
    url: /tag/
    target_blank: false
  - name: About
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true


page_nav_style: ROUND_RECT  # CIRCLE|ROUND_RECT

# Bread Crumb
breadcrumb:
  isShow: true # true|fase

# Box
toolbox:
  isShow: true # true|fase
  text: Box

search_slogan:
  isShow: true # true|fase
  text: Can you find the bug of world ~

link_slogan:
  isShow: true # true|fase
  text: What's this?


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: false
  btn_text: Support me
  tip: Give me money
  items:
    - type: Wechat
      text: Wechat Scan
      imgUrl: /images/qr-wechat.png
    - type: Alipay
      text: Alipay Scan
      imgUrl: /images/qr-alipay.png

post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# Personal settings
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# Third party services
# =========================================================
# Stats
google_analytics: UA-65976996-1
# baidu_analytics: Oh my god who is Baidu?

# Comment service
disqus_shortname: yodahuang
# hypercomments_id: 89821
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

# Valine comment system  https://valine.js.org
valine:
  enable: false # 如果使用valine，请设置改之为true
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size

# 注意，多说即将关闭，建议选用上面四个评论系统
# duoshuo_shortname: forsigner



# 不算子,文章访问量统计和显示
busuanzi: true

# =========================================================
# Page settings
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "Yanda Huang，1995."
    - "Master in Robotics Systems Development"
    - "Carnegie Mellon University"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@yodahuang"
    text_value_url: https://github.com/yodahuang
  - type: mail
    icon: icon-mail
    text_key: E-mail
    text_value: "yanda@cmu.edu"
  - type: location
    icon: icon-location
    text_value: Pittsburgh

project:
  - type: personal
    name: Cabot
    url: https://mrsdprojects.ri.cmu.edu/2017teamg/
    intro: An assistive robot for the visually impaired
    youtube: 5ZCpoQdlMGI
    detail: Click on the title to go to its own website for a more detailed explanation!
    image_alt: Testing
  - type: personal
    name: Automous Navigation in Dynamic Environment
    intro: A Robot that do SLAM and dynamic obstacle avoidence
    youtube: p-G10atUjjI
    detail: The robot implements the algorithm described in the paper <a href="https://web.eecs.umich.edu/~kuipers/papers/Park-iros-12.pdf">Robot Navigation with Model Predictive Equilibrium Point Control</a>
  - type: personal
    name: The Great Finger
    intro: Smart Pointing detector with Stereo Vision
    image: /images/the-great-finger.gif
    image_alt: demo
    detail: Detect and show where the lecturor is pointing at in lecture recordings with the help of stereo vision & machine learning.
    extra: <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vS__5y-ecv7jvSQWAWEfj3tfBZ5gudh0uIqVy2sfXvARnVVgcRWpHKySp_hXnf3KKodnT7BlhFPM752/embed?start=false&loop=false&delayms=3000" frameborder="0" width="498" height="295" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
  - type: personal
    name: NFConnect
    intro: Universal app and hardware solution for NFC devices
    image: /images/nfc.gif
    image_alt: demo
    detail: The Android app communicate with microcontroller that I wrote the firmware on the coffee machine to set timers, brew coffee, etc.
  - type: personal
    name: Pebble GRE Reminder
    url: https://yodahuang.github.io/Pebble-GRE-Word-Reminder/
    intro: A GRE reminder helper for Pebble
    image: /images/pebble-gre-reminder.gif
    detail: This is a appplication for helping reciting GRE words on Pebble smartwatches. The app is published in <a href="https://apps.getpebble.com/en_US/application/577b62526c21040179000074">Pebble App Store</a>. A detailed desciption can be found <a href="https://yodahuang.github.io/Pebble-GRE-Word-Reminder/">here</a>.
    image_alt: the app in action

# =========================================================
# RSS
# =========================================================
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
