# Blog info
blog_name: Yanda's Lab
slogan: The existence of this blog fills you with determination
url: http://yodahuang.github.io
language: en

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /favicon.ico

# For seo
#I don't know what I should advertise
keywords:

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #Don't open in a new page
  - name: Project
    url: /project/
    target_blank: true #Open in a new page
  - name: About me
    url: /about/
    target_blank: false
  - name: My Aria2
    url: http://45.79.103.183/aria2/
    target_blank: true

# config page nav
page_nav:
  - name: Blog
    url: /archives/
    target_blank: false
  - name: Project
    url: /project/
    target_blank: true #Open in a new page
  - name: Category
    url: /category/
    target_blank: false
  - name: Tag
    url: /tag/
    target_blank: false
  - name: About
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true


page_nav_style: ROUND_RECT  # CIRCLE|ROUND_RECT

# Bread Crumb
breadcrumb:
  isShow: true # true|fase

# Box
toolbox:
  isShow: true # true|fase
  text: Box

search_slogan:
  isShow: true # true|fase
  text: Can you find the bug of world ~

link_slogan:
  isShow: true # true|fase
  text: What's this?


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: false
  btn_text: Support me
  tip: Give me money
  items:
    - type: Wechat
      text: Wechat Scan
      imgUrl: /images/qr-wechat.png
    - type: Alipay
      text: Alipay Scan
      imgUrl: /images/qr-alipay.png

post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# Personal settings
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# Third party services
# =========================================================
# Stats
google_analytics: UA-65976996-1
# baidu_analytics: Oh my god who is Baidu?

# Comment service
disqus_shortname: yodahuang

# 不算子,文章访问量统计和显示
busuanzi: true

# =========================================================
# Page settings
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "Yanda Huang，1995."
    - "Currently a Junior student in Univerity of Michigan"
    - "Major in Computer Engineering"
    - "Still don't know where to dive deep in the future."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@yodahuang"
    text_value_url: https://github.com/yodahuang
  - type: mail
    icon: icon-mail
    text_key: Gmail
    text_value: "yodaa@umich.edu"
  - type: location
    icon: icon-location
    text_value: Ann Arbor & Shanghai

project:
  - type: personal
    name: Pebble GRE Reminder
    url: https://yodahuang.github.io/Pebble-GRE-Word-Reminder/
    intro: A GRE reminder helper for Pebble
  - type: personal
    name: Mclickr
    url: https://github.com/yodahuang/Mclicker
    intro: iClickr online!
  - type: company
    name: Data visualizer
    url: https://amazon.com
    intro: "I made this for Amazon, but you can't see it!"

# =========================================================
# RSS
# =========================================================
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
